version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_sb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  inventory-app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      # Override the properties file to point to the docker container named 'mysqldb' instead of localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/inventory_db?allowPublicKeyRetrieval=true&useSSL=false

volumes:
  mysql_data: